AWSTemplateFormatVersion: "2010-09-09"
Description: 'Creates a Route53 private hosted zone for the environment.'

Parameters:
  HostedZoneName:
    Type: String
    Description: 'Private Hosted Zone for Ops Suite environment.'
  VpcId:
    Type: String
    Description: 'ID of the primary VPC.'

Resources:
  rDns:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub 'Hosted Zone for domain ${HostedZoneName} in VPC ${VpcId}'
      Name: !Ref HostedZoneName
      VPCs:
        -
          VPCId: !Ref VpcId
          VPCRegion: !Ref 'AWS::Region'
      HostedZoneTags:
        -
          Key: Name
          Value: !Ref HostedZoneName

Outputs:
  HostedZoneName:
    Description: The fully-qualified domain name.
    Value: !Ref HostedZoneName
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'
  HostedZoneID:
    Description: The ID of the Hosted Zone.
    Value: !Ref rDns
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneID'
